name: Deploy Frontend React
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Actualizar y compilar Frontend vía SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /var/www/sistemaescuelas-frontend
            git checkout main
            git pull origin main
            echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" > .env.production
            npm install
            npm run build
